# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 700)
        MainWindow.setMinimumSize(QtCore.QSize(100, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout_14.addWidget(self.label, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_14.addWidget(self.label_23, 1, 1, 1, 1)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_3.setObjectName("textEdit_3")
        self.gridLayout_6.addWidget(self.textEdit_3, 0, 3, 1, 1)
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_4.setObjectName("textEdit_4")
        self.gridLayout_3.addWidget(self.textEdit_4, 1, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.gridLayout_14.addWidget(self.tabWidget_3, 2, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setMaximumSize(QtCore.QSize(480, 16777215))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 3)
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 3, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_4.addWidget(self.radioButton_4, 1, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_4.addWidget(self.radioButton_5, 1, 1, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout_4.addWidget(self.radioButton_6, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 2)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_5.addWidget(self.pushButton_7, 10, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 16, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_5.addWidget(self.pushButton_10, 13, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 9, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_5.addWidget(self.pushButton_8, 11, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 9, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_5.addWidget(self.spinBox_5, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/icons/icons/SigS.png"))
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 12, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/icons/icons/SigT.png"))
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 10, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_5.addWidget(self.comboBox, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 3, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_5.addWidget(self.spinBox_3, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/icons/icons/SigF.png"))
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 11, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_3)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/icons/icons/Chi.png"))
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 13, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 6, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_5.addWidget(self.pushButton_9, 12, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_5.addWidget(self.spinBox, 2, 1, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_5.addWidget(self.spinBox_2, 3, 1, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_5.addWidget(self.spinBox_4, 5, 1, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_5.addWidget(self.spinBox_6, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 7, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 8, 0, 1, 1)
        self.spinBox_7 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_7.setObjectName("spinBox_7")
        self.gridLayout_5.addWidget(self.spinBox_7, 8, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 17, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_4, 8, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setObjectName("label_21")
        self.gridLayout_9.addWidget(self.label_21, 9, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_9.addWidget(self.pushButton_2, 10, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_9.addWidget(self.label_27, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_9.addWidget(self.pushButton_5, 14, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 6, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_3, 7, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_9.addWidget(self.comboBox_2, 5, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_9.addWidget(self.pushButton_3, 11, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_4)
        self.label_22.setObjectName("label_22")
        self.gridLayout_9.addWidget(self.label_22, 12, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_9.addWidget(self.pushButton_4, 13, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_9.addWidget(self.pushButton_11, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_5 = QtWidgets.QFrame(self.tab_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 0, 1, 1, 1)
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_11.addWidget(self.radioButton_9, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_5, 0, 0, 1, 2)
        self.frame_6 = QtWidgets.QFrame(self.tab_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_12.addWidget(self.pushButton_13, 13, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_6)
        self.label_35.setObjectName("label_35")
        self.gridLayout_12.addWidget(self.label_35, 0, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_6)
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap(":/icons/icons/SigT.png"))
        self.label_36.setObjectName("label_36")
        self.gridLayout_12.addWidget(self.label_36, 11, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_12.addWidget(self.pushButton_17, 11, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_6)
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap(":/icons/icons/SigF.png"))
        self.label_26.setObjectName("label_26")
        self.gridLayout_12.addWidget(self.label_26, 12, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_12.addWidget(self.pushButton_15, 12, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.frame_6)
        self.label_40.setText("")
        self.label_40.setPixmap(QtGui.QPixmap(":/icons/icons/SigS.png"))
        self.label_40.setObjectName("label_40")
        self.gridLayout_12.addWidget(self.label_40, 13, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_6)
        self.label_34.setText("")
        self.label_34.setPixmap(QtGui.QPixmap(":/icons/icons/Chi.png"))
        self.label_34.setObjectName("label_34")
        self.gridLayout_12.addWidget(self.label_34, 14, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_12.addWidget(self.pushButton_14, 14, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem2, 17, 0, 1, 1)
        self.comboBox_8 = QtWidgets.QComboBox(self.frame_6)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.gridLayout_12.addWidget(self.comboBox_8, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBox_8 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_8.setObjectName("spinBox_8")
        self.gridLayout_12.addWidget(self.spinBox_8, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.frame_6)
        self.label_43.setObjectName("label_43")
        self.gridLayout_12.addWidget(self.label_43, 8, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.frame_6)
        self.label_38.setObjectName("label_38")
        self.gridLayout_12.addWidget(self.label_38, 7, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.frame_6)
        self.label_44.setObjectName("label_44")
        self.gridLayout_12.addWidget(self.label_44, 9, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.frame_6)
        self.label_42.setObjectName("label_42")
        self.gridLayout_12.addWidget(self.label_42, 6, 0, 1, 1)
        self.spinBox_15 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_15.setObjectName("spinBox_15")
        self.gridLayout_12.addWidget(self.spinBox_15, 8, 1, 1, 1)
        self.spinBox_13 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_13.setObjectName("spinBox_13")
        self.gridLayout_12.addWidget(self.spinBox_13, 7, 1, 1, 1)
        self.spinBox_16 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_16.setObjectName("spinBox_16")
        self.gridLayout_12.addWidget(self.spinBox_16, 9, 1, 1, 1)
        self.spinBox_10 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_10.setObjectName("spinBox_10")
        self.gridLayout_12.addWidget(self.spinBox_10, 3, 1, 1, 1)
        self.spinBox_11 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_11.setObjectName("spinBox_11")
        self.gridLayout_12.addWidget(self.spinBox_11, 5, 1, 1, 1)
        self.spinBox_12 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_12.setObjectName("spinBox_12")
        self.gridLayout_12.addWidget(self.spinBox_12, 6, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.frame_6)
        self.label_37.setObjectName("label_37")
        self.gridLayout_12.addWidget(self.label_37, 10, 0, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_12.addWidget(self.pushButton_23, 10, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.frame_6)
        self.label_39.setObjectName("label_39")
        self.gridLayout_12.addWidget(self.label_39, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_6)
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 5, 0, 1, 1)
        self.spinBox_9 = QtWidgets.QSpinBox(self.frame_6)
        self.spinBox_9.setObjectName("spinBox_9")
        self.gridLayout_12.addWidget(self.spinBox_9, 4, 1, 1, 1)
        self.gridLayout_15.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.tab_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_31 = QtWidgets.QLabel(self.frame_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_13.addWidget(self.label_31, 13, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_6, 8, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_13.addWidget(self.pushButton_20, 15, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_13.addWidget(self.pushButton_18, 14, 0, 1, 1)
        self.comboBox_11 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_11, 5, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_13.addWidget(self.pushButton_12, 10, 0, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_9, 4, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.frame_7)
        self.label_29.setObjectName("label_29")
        self.gridLayout_13.addWidget(self.label_29, 7, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_13.addWidget(self.label_28, 9, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_7)
        self.label_30.setObjectName("label_30")
        self.gridLayout_13.addWidget(self.label_30, 2, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_13.addWidget(self.pushButton_22, 11, 0, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_10, 6, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_13.addWidget(self.pushButton_21, 12, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem3, 16, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_13.addWidget(self.comboBox_5, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.frame_7)
        self.label_33.setObjectName("label_33")
        self.gridLayout_13.addWidget(self.label_33, 0, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_13.addWidget(self.pushButton_16, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_7, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_14.addWidget(self.tabWidget, 1, 0, 2, 1)
        self.label.raise_()
        self.label_23.raise_()
        self.tabWidget.raise_()
        self.tabWidget_3.raise_()
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 955, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setSeparatorsCollapsible(False)
        self.menuFile.setObjectName("menuFile")
        self.menu_Geometry = QtWidgets.QMenu(self.menuFile)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/geometry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_Geometry.setIcon(icon)
        self.menu_Geometry.setSeparatorsCollapsible(True)
        self.menu_Geometry.setObjectName("menu_Geometry")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setObjectName("menu_View")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Run = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/run.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Run.setIcon(icon1)
        self.action_Run.setIconVisibleInMenu(True)
        self.action_Run.setObjectName("action_Run")
        self.action_Plot = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Plot.setIcon(icon2)
        self.action_Plot.setIconVisibleInMenu(True)
        self.action_Plot.setObjectName("action_Plot")
        self.action_New = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/new_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_New.setIcon(icon3)
        self.action_New.setIconVisibleInMenu(True)
        self.action_New.setObjectName("action_New")
        self.action_Open = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/open_file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Open.setIcon(icon4)
        self.action_Open.setIconVisibleInMenu(True)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save.setIcon(icon5)
        self.action_Save.setIconVisibleInMenu(True)
        self.action_Save.setObjectName("action_Save")
        self.action_Save_as = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Save_as.setIcon(icon6)
        self.action_Save_as.setIconVisibleInMenu(True)
        self.action_Save_as.setObjectName("action_Save_as")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/exit_editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon7)
        self.action_Exit.setIconVisibleInMenu(True)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Slab = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/slab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Slab.setIcon(icon8)
        self.action_Slab.setIconVisibleInMenu(True)
        self.action_Slab.setObjectName("action_Slab")
        self.action_Sphere = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/sphere.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Sphere.setIcon(icon9)
        self.action_Sphere.setIconVisibleInMenu(True)
        self.action_Sphere.setObjectName("action_Sphere")
        self.action_Cylinder = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/cylinder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cylinder.setIcon(icon10)
        self.action_Cylinder.setIconVisibleInMenu(True)
        self.action_Cylinder.setObjectName("action_Cylinder")
        self.action_Compile_2 = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/compile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Compile_2.setIcon(icon11)
        self.action_Compile_2.setShortcut("")
        self.action_Compile_2.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.action_Compile_2.setVisible(True)
        self.action_Compile_2.setIconVisibleInMenu(True)
        self.action_Compile_2.setPriority(QtWidgets.QAction.NormalPriority)
        self.action_Compile_2.setObjectName("action_Compile_2")
        self.action_Undo = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Undo.setIcon(icon12)
        self.action_Undo.setIconVisibleInMenu(True)
        self.action_Undo.setObjectName("action_Undo")
        self.action_Redo = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Redo.setIcon(icon13)
        self.action_Redo.setIconVisibleInMenu(True)
        self.action_Redo.setObjectName("action_Redo")
        self.action_Cut = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Cut.setIcon(icon14)
        self.action_Cut.setIconVisibleInMenu(True)
        self.action_Cut.setObjectName("action_Cut")
        self.action_Copy = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/icons/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Copy.setIcon(icon15)
        self.action_Copy.setIconVisibleInMenu(True)
        self.action_Copy.setObjectName("action_Copy")
        self.action_Paste = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/icons/icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Paste.setIcon(icon16)
        self.action_Paste.setIconVisibleInMenu(True)
        self.action_Paste.setObjectName("action_Paste")
        self.action_Find = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/icons/icons/on_find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Find.setIcon(icon17)
        self.action_Find.setIconVisibleInMenu(True)
        self.action_Find.setObjectName("action_Find")
        self.action_Select_All = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/icons/icons/Select_All.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Select_All.setIcon(icon18)
        self.action_Select_All.setIconVisibleInMenu(True)
        self.action_Select_All.setObjectName("action_Select_All")
        self.action_Help = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/icons/help_box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Help.setIcon(icon19)
        self.action_Help.setIconVisibleInMenu(True)
        self.action_Help.setObjectName("action_Help")
        self.action_About = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_About.setIcon(icon20)
        self.action_About.setIconVisibleInMenu(True)
        self.action_About.setObjectName("action_About")
        self.action_website = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/icons/web.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_website.setIcon(icon21)
        self.action_website.setIconVisibleInMenu(True)
        self.action_website.setObjectName("action_website")
        self.action_About_Qt = QtWidgets.QAction(MainWindow)
        self.action_About_Qt.setObjectName("action_About_Qt")
        self.menu_Geometry.addAction(self.action_Slab)
        self.menu_Geometry.addAction(self.action_Sphere)
        self.menu_Geometry.addAction(self.action_Cylinder)
        self.menuFile.addAction(self.action_Compile_2)
        self.menuFile.addAction(self.action_Run)
        self.menuFile.addAction(self.action_Plot)
        self.menuFile.addAction(self.menu_Geometry.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_New)
        self.menuFile.addAction(self.action_Open)
        self.menuFile.addAction(self.action_Save)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Save_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_Exit)
        self.menu_Edit.addAction(self.action_Undo)
        self.menu_Edit.addAction(self.action_Redo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Cut)
        self.menu_Edit.addAction(self.action_Copy)
        self.menu_Edit.addAction(self.action_Paste)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Find)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_Select_All)
        self.menu_About.addAction(self.action_Help)
        self.menu_About.addSeparator()
        self.menu_About.addAction(self.action_About)
        self.menu_About.addAction(self.action_website)
        self.menu_About.addAction(self.action_About_Qt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.toolBar.addAction(self.action_Compile_2)
        self.toolBar.addAction(self.action_Run)
        self.toolBar.addAction(self.action_Plot)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_New)
        self.toolBar.addAction(self.action_Open)
        self.toolBar.addAction(self.action_Save)
        self.toolBar.addAction(self.action_Save_as)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Undo)
        self.toolBar.addAction(self.action_Redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Cut)
        self.toolBar.addAction(self.action_Copy)
        self.toolBar.addAction(self.action_Paste)
        self.toolBar.addAction(self.action_Select_All)
        self.toolBar.addAction(self.action_Find)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Help)
        self.toolBar.addAction(self.action_About)
        self.toolBar.addAction(self.action_website)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Exit)

        self.retranslateUi(MainWindow)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Computational Dimension"))
        self.label_23.setText(_translate("MainWindow", "Notebooks"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Output Window"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Input Window"))
        font1 = QtGui.QFont("Courier", 10)
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setWeight(30)
        font2 = QtGui.QFont("Courier", 10)
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setWeight(30)
        self.textEdit_3.setFont(font1)
        self.textEdit_4.setFont(font2)





        self.label_14.setText(_translate("MainWindow", " Calculation Method "))
        self.radioButton_4.setText(_translate("MainWindow", "CP"))
        self.radioButton_5.setText(_translate("MainWindow", "Sɴ"))
        self.radioButton_6.setText(_translate("MainWindow", "&MOC"))
        self.pushButton_7.setText(_translate("MainWindow", "Insert"))
        self.pushButton_10.setText(_translate("MainWindow", "Insert"))
        self.pushButton.setText(_translate("MainWindow", "Insert"))
        self.pushButton_8.setText(_translate("MainWindow", "Insert"))
        self.label_20.setText(_translate("MainWindow", "Size/NFMR/Materials :"))
        self.label_6.setText(_translate("MainWindow", "Number of Materials :"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Slab Geometry"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Cylindrical Geometry"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Spherical Geometry"))
        self.label_7.setText(_translate("MainWindow", "Angular Discretization :"))
        self.label_4.setText(_translate("MainWindow", "Energy Group Number :"))
        self.label_2.setText(_translate("MainWindow", "Input Parameters :"))
        self.label_5.setText(_translate("MainWindow", "Number of Regions :"))
        self.label_8.setText(_translate("MainWindow", "Legendre Order :"))
        self.pushButton_9.setText(_translate("MainWindow", "Insert"))
        self.label_12.setText(_translate("MainWindow", "Maximum Iterations :"))
        self.label_13.setText(_translate("MainWindow", "Tolerance : 1e\u207F"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Step Characteristics"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "DD0"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "DD1"))
        self.label_21.setText(_translate("MainWindow", "Plots"))
        self.pushButton_2.setText(_translate("MainWindow", "Geometry"))
        self.label_27.setText(_translate("MainWindow", "Generate Input File"))
        self.pushButton_5.setText(_translate("MainWindow", "Run"))
        self.label_10.setText(_translate("MainWindow", " Approximation Scheme"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Step Difference"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Diamond Difference"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Vacuum"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Reflective"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Vacuum Reflective"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Reflective Vacuum"))
        self.pushButton_3.setText(_translate("MainWindow", "Scalar Flux"))
        self.label_22.setText(_translate("MainWindow", "Controles"))
        self.pushButton_4.setText(_translate("MainWindow", "Compile"))
        self.pushButton_11.setText(_translate("MainWindow", "Data Up"))
        self.label_9.setText(_translate("MainWindow", " Boundary Conditions"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "One-Dimensional"))
        self.radioButton_9.setText(_translate("MainWindow", "SN"))
        self.label_25.setText(_translate("MainWindow", " Calculation Method "))
        self.pushButton_13.setText(_translate("MainWindow", "Insert"))
        self.label_35.setText(_translate("MainWindow", "Input Parameters "))
        self.pushButton_17.setText(_translate("MainWindow", "Insert"))
        self.pushButton_15.setText(_translate("MainWindow", "Insert"))
        self.pushButton_14.setText(_translate("MainWindow", "Insert"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "Cartesian Geometry"))
        self.label_3.setText(_translate("MainWindow", "Energy Group Number :"))
        self.label_43.setText(_translate("MainWindow", "Maximum Iterations :"))
        self.label_38.setText(_translate("MainWindow", "Legendre Order :"))
        self.label_44.setText(_translate("MainWindow", "Tolerance : 1e\u207F"))
        self.label_42.setText(_translate("MainWindow", "Angular Discretization :"))
        self.label_37.setText(_translate("MainWindow", "Size/NFMR/Materials :"))
        self.pushButton_23.setText(_translate("MainWindow", "Insert"))
        self.label_39.setText(_translate("MainWindow", "Number of X Regions :"))
        self.label_11.setText(_translate("MainWindow", "Number of Materials :"))
        self.label_32.setText(_translate("MainWindow", "Number of Y Regions :"))
        self.label_31.setText(_translate("MainWindow", "Controles"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Step Difference"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Diamond Difference"))
        self.pushButton_20.setText(_translate("MainWindow", "Run"))
        self.pushButton_18.setText(_translate("MainWindow", "Compile"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "Vacuum Bottom"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "Reflective Bottom"))
        self.pushButton_12.setText(_translate("MainWindow", "Geometry"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "Vacuum Left "))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "Reflective Left"))
        self.label_29.setText(_translate("MainWindow", " Approximation Scheme"))
        self.label_28.setText(_translate("MainWindow", "Plots"))
        self.label_30.setText(_translate("MainWindow", " Boundary Conditions"))
        self.pushButton_22.setText(_translate("MainWindow", "Ordinates"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "Vacuum Top"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "Reflective Top"))
        self.pushButton_21.setText(_translate("MainWindow", "Scalar Flux"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Vacuum Right"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Reflective Right"))
        self.label_33.setText(_translate("MainWindow", "Generate Input File"))
        self.pushButton_16.setText(_translate("MainWindow", "Data Up"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Two-Dimensional"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menu_Geometry.setTitle(_translate("MainWindow", "&Geometry"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.menu_About.setTitle(_translate("MainWindow", "&Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_Run.setText(_translate("MainWindow", "&Run"))
        self.action_Plot.setText(_translate("MainWindow", "&Plot"))
        self.action_New.setText(_translate("MainWindow", "&New"))
        self.action_Open.setText(_translate("MainWindow", "&Open"))
        self.action_Save.setText(_translate("MainWindow", "&Save"))
        self.action_Save_as.setText(_translate("MainWindow", "Sa&ve as"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))
        self.action_Slab.setText(_translate("MainWindow", "&Slab"))
        self.action_Sphere.setText(_translate("MainWindow", "S&phere"))
        self.action_Cylinder.setText(_translate("MainWindow", "&Cylinder"))
        self.action_Compile_2.setText(_translate("MainWindow", "&Compile", "Ctrl+E"))
        self.action_Undo.setText(_translate("MainWindow", "&Undo"))
        self.action_Redo.setText(_translate("MainWindow", "&Redo"))
        self.action_Cut.setText(_translate("MainWindow", "&Cut"))
        self.action_Copy.setText(_translate("MainWindow", "C&opy"))
        self.action_Paste.setText(_translate("MainWindow", "&Paste"))
        self.action_Find.setText(_translate("MainWindow", "&Find"))
        self.action_Select_All.setText(_translate("MainWindow", "&Select All"))
        self.action_Help.setText(_translate("MainWindow", "&Help"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_website.setText(_translate("MainWindow", "&website"))
        self.action_About_Qt.setText(_translate("MainWindow", "About &Qt"))

import test_rc
